before_script:
    - apt-get update
    - apt-get install -y expect-dev python-lxml python-simplejson python-serial python-yaml
    - git clone https://github.com/steingabelgaard/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
    - export MAKEPOT="1" 
    - travis_install_nightly
  
makemypot:
    stage: test
    script:
        - travis_run_tests

