from . import campos_group_reg
from . import campos_age_group
from . import campos_camp_period
from . import campos_prereg_age_period
from . import cms_form_campos_group_reg
from . import res_partner
from . import campos_scout_org
from . import account_form
from . import campos_participant
from . import campos_camp_day
from . import cms_form_campos_participant
#from . import campos_participant_day
